name: Clone and Replace Repository

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  clone-and-replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Another Repository
        run: |
          git clone --depth=1 https://github.com/username/another-repo.git temp-repo
          rsync -a temp-repo/ ./
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Replace existing repository with cloned content"
          git push
        env:
          PAT_TOKEN: ${{ secrets.TOKEN }}
